"""
Text-to-SQL chatbot for weather station queries.

Flow:
1. Classify the message as small talk (greetings/thanks/acknowledgments), a
   station-info question, or a data question. Classification is done by the
   LLM; a regex-based keyword match is used only as a fallback if that call
   fails.
2. Small-talk/station-info replies are generated by the LLM (grounded with
   static station facts and, for small talk, the conversation history so it
   can tell an opener from a closing acknowledgment).
3. Data questions are turned into a read-only SQL query by the LLM, given
   the DB schema, then executed and summarized back into natural language.

Uses Ollama Cloud (gpt-oss:20b-cloud) via its OpenAI-compatible API instead
of a paid LLM API — free tier, no AWS compute to host a model ourselves.
See https://ollama.com/pricing and https://docs.ollama.com/cloud.

Safety constraints on generated SQL:
- Only SELECT statements are allowed (checked before execution).
- Only whitelisted tables/columns are exposed in the prompt schema.
- Query runs against a DB role with SELECT-only privileges (see README).
- A LIMIT is enforced if the model omits one.

Streaming:
- The pipeline is exposed as `classify_and_reply`, a generator that yields
  progress dicts as the request moves through the pipeline (stage changes,
  reply tokens) and returns the final result dict (intent/reply/sql) via
  StopIteration.value. Callers that just want the final result (e.g. the
  internal COUNT check in answer_data_question) can drain the generator
  with `run_to_completion`.
"""

import json
import logging
import re
from datetime import datetime, timezone

from openai import OpenAI
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.config import settings

logger = logging.getLogger(__name__)

client = OpenAI(base_url="https://ollama.com/v1", api_key=settings.ollama_api_key)

MODEL = "gpt-oss:20b-cloud"

SCHEMA_DESCRIPTION = """
Table: readings (one row per station per second)
  - time            TIMESTAMPTZ  -- when the reading was taken
  - station_id       INTEGER      -- FK to stations.id
  - temperature_c    DOUBLE PRECISION
  - humidity_pct     DOUBLE PRECISION
  - pressure_hpa     DOUBLE PRECISION
  - wind_speed_ms    DOUBLE PRECISION
  - wind_dir_deg     DOUBLE PRECISION
  - noise_db         DOUBLE PRECISION
  - pm2_5_ugm3       DOUBLE PRECISION
  - pm10_ugm3        DOUBLE PRECISION

Table: stations
  - id          SERIAL PRIMARY KEY
  - name        TEXT
  - location    TEXT
  - latitude    DOUBLE PRECISION
  - longitude   DOUBLE PRECISION
  - created_at  TIMESTAMPTZ  -- when the station was registered
"""

# Matches frontend/src/metrics.js -- the one source of truth for which unit
# each sensor column is recorded in, given to the SQL generator so it aliases
# result columns with the unit baked in (e.g. avg_temperature_c), instead of
# leaving the summarizer to guess a unit from an arbitrary alias afterward.
COLUMN_UNITS = {
    "temperature_c": "°C",
    "humidity_pct": "%",
    "pressure_hpa": "hPa",
    "wind_speed_ms": "m/s",
    "wind_dir_deg": "°",
    "noise_db": "dB",
    "pm2_5_ugm3": "µg/m³",
    "pm10_ugm3": "µg/m³",
}
COLUMN_UNITS_DESCRIPTION = "\n".join(f"  - {col}: {unit}" for col, unit in COLUMN_UNITS.items())

STATION_FACTS = """
This weather station is a Raspberry Pi based setup that measures temperature,
humidity, atmospheric pressure, wind speed/direction, noise level, and
PM2.5/PM10 particulate matter concentration once per second, and streams the
readings to a cloud database in real time. Users can ask this chatbot
questions about the station's recorded data in natural language.

What each measured metric is:
- Temperature (°C): the air temperature at the station.
- Humidity (%): relative humidity, how much moisture the air is holding
  relative to the maximum it could hold at that temperature.
- Pressure (hPa): atmospheric (barometric) pressure at the station.
- Wind speed (m/s): how fast the air is moving.
- Wind direction (°): the compass direction the wind is blowing FROM, in
  degrees (0/360 = north, 90 = east, 180 = south, 270 = west).
- Noise (dB): ambient sound level in decibels.
- PM2.5 (µg/m³): concentration of fine airborne particulate matter 2.5
  micrometers or smaller in diameter, small enough to be inhaled deep into
  the lungs (e.g. from smoke, vehicle exhaust, dust). Higher values mean
  worse air quality.
- PM10 (µg/m³): concentration of airborne particulate matter 10 micrometers
  or smaller in diameter (a broader size range than PM2.5, includes things
  like pollen and larger dust). Higher values mean worse air quality.
"""

SMALL_TALK_PATTERNS = re.compile(
    r"^\s*(hi|hello|hey|good (morning|afternoon|evening)|greetings"
    r"|thanks|thank you|thx|ok(ay)?|cool|great|perfect|nice|got it|sounds good|no problem|you'?re welcome|bye|goodbye)\b",
    re.IGNORECASE,
)
STATION_INFO_PATTERNS = re.compile(
    r"\b(what (are|is) you|who are you|what do you do|tell me about (this|the) station|how does (this|the) station work|what.*(this )?(app|application) (do|for)"
    r"|what (is|are|does).*(mean|measure)|pm ?2\.?5|pm ?10\b)\b",
    re.IGNORECASE,
)

INTENTS = ("small_talk", "station_info", "data_question", "unclear")

STYLE_RULE = "Do not use emojis. Do not use em dashes or double hyphens (--); use a comma or period instead."

DASH_PATTERN = re.compile(r"\s*(--|[–—])\s*")
TABLE_ROW_PATTERN = re.compile(r"^\s*\|?[\s:|-]+\|?\s*$")


def enforce_style(text: str) -> str:
    lines = text.split("\n")
    fixed_lines = [
        line if TABLE_ROW_PATTERN.match(line) else DASH_PATTERN.sub(", ", line)
        for line in lines
    ]
    return "\n".join(fixed_lines).strip()

# Shared, single source of truth for how every stage (classification, SQL
# generation) resolves a short follow-up against conversation history. This
# used to be a separately hand-written, drifting instruction in each prompt
# below (patched repeatedly, once per bug report); it is now one general
# rule both prompts include, so a future fix to "how follow-ups resolve"
# only has to change one place instead of two.
CONTEXT_RESOLUTION_RULE = """A message may be a short follow-up that only makes sense in light of
the conversation history, rather than a complete, self-contained question. There are three
kinds of follow-up, and none of them can be judged on their own text alone -- always read the
conversation history first:
1. SLOT CHANGE: modifies part of the previous data question. Model every data question as a
   set of independent slots: STATION, METRIC, TIME RANGE, and AGGREGATE (avg/min/max/raw/etc).
   The follow-up updates only the slot(s) it explicitly names; every other slot keeps
   whatever value was most recently established earlier in the conversation, and is never
   reset just because the follow-up doesn't repeat it.
   Example: "give me july 31 temperature" establishes METRIC=temperature, TIME RANGE=july 31.
   "highest?" then changes only AGGREGATE=max, leaving METRIC and TIME RANGE unchanged, so the
   answer is the highest temperature ON JULY 31, not an all-time maximum. "What about last
   month?" changes only TIME RANGE, keeping the established METRIC.
2. REPEAT: asks to redo the previous data question unchanged (e.g. "retry", "try again",
   "one more time"). Treat this exactly like the previous data question, with all slots kept
   as they were.
3. CLARIFY: asks about the previous answer itself rather than requesting new data (e.g.
   "when?", "which station was that?", "what units?"). Answer using the slots already
   established for the previous data question -- do not treat it as unclear just because it
   names no metric or time range of its own.
In all three cases, resolve the message against the full conversation history before acting;
never interpret it in isolation from what came before."""

CLASSIFY_SYSTEM_PROMPT = f"""Classify the user's message into exactly one intent:
- "small_talk": greetings, acknowledgments, thanks, or other conversational chatter with no
  information request (e.g. "hello", "thanks", "okay perfect", "great, thank you").
- "station_info": a question about what this chatbot or weather station is/does/can do, or
  what one of its measured metrics means/is (e.g. "what is PM2.5", "what does humidity mean",
  "what unit is pressure in") -- a definition question, not a request for recorded data.
- "data_question": a question asking about actual sensor readings or historical data.
- "unclear": anything else that doesn't fit the categories above, or is too vague to act on.

{CONTEXT_RESOLUTION_RULE}
If, once resolved against the history, the message is a slot change, a repeat, or a
clarification of a prior data question, classify it as "data_question" even when it
is short and names no metric or time range of its own (e.g. "lowest?", "retry", "when?").
Only classify as "unclear" if it is still ambiguous after considering the history.

Respond with ONLY a JSON object: {{"intent": "<one of {list(INTENTS)}>"}}"""

TOO_BROAD_SENTINEL = "TOO_BROAD"

RAW_ROW_LIMIT = 5
AGGREGATE_ROW_LIMIT = 100

SQL_SYSTEM_PROMPT_TEMPLATE = f"""You are a SQL generator for a PostgreSQL weather database.
The current date and time is {{now}}. Resolve any relative or year-less date the
user gives (e.g. "July 30", "yesterday", "last week") against this current date,
never against a guessed or remembered year.
Schema:
{SCHEMA_DESCRIPTION}
Units (each column is always recorded in this unit, never any other):
{COLUMN_UNITS_DESCRIPTION}

Rules:
- Output ONLY a single read-only SQL SELECT statement, nothing else — no
  explanation, no markdown fences, no commentary before or after.
- Never use INSERT, UPDATE, DELETE, DROP, ALTER, or any DDL/DML.
- Always alias every selected/aggregated column so the base column name is
  still visible in the alias (e.g. AVG(temperature_c) AS avg_temperature_c,
  not AS avg_temp or AS result) — the unit is looked up from that base column
  name afterward, so an alias that drops or renames it loses the unit.
- readings has one row per station per second, so it grows very large.
  Raw (non-aggregated) queries — selecting individual reading rows rather
  than a GROUP BY summary — must almost always include a LIMIT of at most
  {RAW_ROW_LIMIT} and should target only a very recent, narrow window (e.g.
  "the last few readings", "the most recent reading a few minutes ago") —
  never a broad raw window like "the past hour" or "the past day" of
  individual rows.
- Aggregate queries (GROUP BY / date_trunc bucketing, e.g. daily or hourly
  averages) may return up to {AGGREGATE_ROW_LIMIT} rows — e.g. daily
  averages over about {AGGREGATE_ROW_LIMIT} days (a bit over 3 months), or
  hourly averages over about 4 days. Always include a LIMIT unless the
  aggregate collapses to a single row.
- Use time-bucketing (date_trunc) for "per day/week" style questions.
- Default to the most recent station if none is named.
- {CONTEXT_RESOLUTION_RULE}
  Generate SQL from the fully resolved slots (station, metric, time range,
  aggregate), never from the latest message read in isolation.
- If the user asks for raw readings over a broad window (e.g. "all raw data",
  "every reading for the past hour/day/week", "dump the whole table") or an
  aggregate over a window wider than about {AGGREGATE_ROW_LIMIT} buckets,
  do NOT generate a query. Instead output exactly: {TOO_BROAD_SENTINEL}
"""

FORBIDDEN_SQL = re.compile(
    r"\b(insert|update|delete|drop|alter|truncate|grant|revoke|create)\b", re.IGNORECASE
)


def history_to_messages(history: list[tuple[str, str]]) -> list[dict]:
    return [
        {"role": "assistant" if role == "assistant" else "user", "content": text}
        for role, text in history
    ]


def run_to_completion(generator):
    """Drain a pipeline generator, discarding progress events, and return its final result."""
    try:
        while True:
            next(generator)
    except StopIteration as stop:
        return stop.value


def classify_intent(message: str, history: list[tuple[str, str]]) -> str:
    try:
        response = client.chat.completions.create(
            model=MODEL,
            # "high" reasoning effort needs headroom for its internal
            # reasoning trace before it emits the final JSON; a low
            # max_tokens here truncates that trace mid-thought, produces no
            # parseable JSON, and silently drops every call into the
            # keyword-only fallback below (which misclassifies almost
            # everything as "unclear").
            max_tokens=1500,
            extra_body={"reasoning_effort": "high"},
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": CLASSIFY_SYSTEM_PROMPT},
                *history_to_messages(history),
                {"role": "user", "content": message},
            ],
        )
        raw_content = response.choices[0].message.content
        intent = json.loads(raw_content)["intent"]
        if intent in INTENTS:
            return intent
        logger.warning(
            "classify_intent: LLM returned unrecognized intent %r for message %r (raw: %r)",
            intent, message, raw_content,
        )
    except Exception:
        logger.exception("classify_intent: LLM classification call failed for message %r", message)

    if SMALL_TALK_PATTERNS.search(message):
        return "small_talk"
    if STATION_INFO_PATTERNS.search(message):
        return "station_info"
    return "unclear"


def stream_reply(messages: list[dict], max_tokens: int, reasoning_effort: str = "low"):
    """Stream a chat completion, yielding {"type": "token", "text": ...} per chunk.

    Returns (via StopIteration.value) the full, style-enforced reply text.
    """
    stream = client.chat.completions.create(
        model=MODEL,
        max_tokens=max_tokens,
        extra_body={"reasoning_effort": reasoning_effort},
        messages=messages,
        stream=True,
    )
    chunks = []
    for chunk in stream:
        delta = chunk.choices[0].delta.content
        if delta:
            chunks.append(delta)
            yield {"type": "token", "text": delta}
    return enforce_style("".join(chunks))


def reply_to_small_talk(message: str, history: list[tuple[str, str]]):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a friendly assistant for a weather station app. The user's latest "
                "message is small talk (a greeting, thanks, or a short acknowledgment), not a "
                "data question. Look at the conversation history to tell whether this opens the "
                "conversation or just closes out a prior answer. If it opens the conversation, "
                "reply in one short sentence and invite them to ask about temperature, humidity, "
                "pressure, or other readings. If it just acknowledges/thanks you for a prior "
                f"answer, reply with a brief one-sentence acknowledgment and nothing more, do "
                f"not restate or re-summarize the previous answer. {STYLE_RULE}"
            ),
        },
        *history_to_messages(history),
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=300))


def reply_to_unclear(message: str):
    messages = [
        {
            "role": "system",
            "content": f"You are the assistant for a weather station app. The user's message doesn't clearly ask about the station's data or about the app itself. In one short sentence, say you didn't understand and invite them to ask about the station. {STYLE_RULE}",
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=300))


def reply_to_station_info(message: str):
    messages = [
        {
            "role": "system",
            "content": f"You are the assistant for a weather station app. Answer the user's question about the station/app in 3 sentences or fewer, using these facts:\n{STATION_FACTS}\n{STYLE_RULE}",
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=600))


def classify_and_reply(message: str, db: Session, history: list[tuple[str, str]] = []):
    yield {"type": "stage", "stage": "classifying"}
    intent = classify_intent(message, history)

    if intent == "small_talk":
        reply = yield from reply_to_small_talk(message, history)
        return {"intent": "small_talk", "reply": reply, "sql": None}

    if intent == "station_info":
        reply = yield from reply_to_station_info(message)
        return {"intent": "station_info", "reply": reply, "sql": None}

    if intent == "unclear":
        reply = yield from reply_to_unclear(message)
        return {"intent": "unclear", "reply": reply, "sql": None}

    result = yield from answer_data_question(message, db, history)
    return result


GROUP_BY_PATTERN = re.compile(r"\bgroup\s+by\b", re.IGNORECASE)


def row_limit_for(sql: str) -> int:
    """Raw per-reading queries get a much tighter cap than bucketed aggregates."""
    return AGGREGATE_ROW_LIMIT if GROUP_BY_PATTERN.search(sql) else RAW_ROW_LIMIT


def reply_to_too_broad(message: str):
    messages = [
        {
            "role": "system",
            "content": (
                "You are the assistant for a weather station app. Readings are recorded "
                "every 30 seconds per station, so the user's request below would return too "
                "much data. Explain that to the user referencing what they specifically asked "
                "for, then propose 2-3 concrete narrower alternatives that this system can "
                f"actually satisfy — you MUST stay within these hard limits, do not suggest "
                f"anything broader:\n"
                f"- Raw (individual, non-aggregated) readings: at most {RAW_ROW_LIMIT} rows, "
                f"so only offer something like \"the most recent reading\" or \"the last "
                f"{RAW_ROW_LIMIT} readings\" (a couple of minutes at most) — never a raw window "
                f"like \"the past hour\" or \"the past day.\"\n"
                f"- Aggregated data (an average/min/max per hour or day): up to "
                f"{AGGREGATE_ROW_LIMIT} rows, e.g. daily averages over about "
                f"{AGGREGATE_ROW_LIMIT} days (roughly 3 months) or hourly averages over about "
                f"4 days.\n"
                f"Prefer the aggregate option when the user's original time range was long. "
                f"{STYLE_RULE}"
            ),
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=600, reasoning_effort="medium"))


MAX_ATTEMPTS = 3


def answer_data_question(message: str, db: Session, history: list[tuple[str, str]] = []):
    feedback = None

    for attempt in range(MAX_ATTEMPTS):
        yield {"type": "stage", "stage": "generating_sql" if attempt == 0 else "retrying_query"}
        sql = generate_sql(message, history, feedback)

        if sql.strip().upper() == TOO_BROAD_SENTINEL:
            reply = yield from reply_to_too_broad(message)
            return {"intent": "sql_query", "reply": reply, "sql": None}

        yield {"type": "stage", "stage": "running_query"}
        try:
            validate_readonly(sql)
            count = db.scalar(text(f"SELECT COUNT(*) FROM ({sql.rstrip(';')}) AS sub"))
        except Exception as e:
            db.rollback()
            feedback = f"The previous query:\n{sql}\nfailed with error: {e}. Fix it."
            continue

        max_rows = row_limit_for(sql)
        if count > max_rows:
            if attempt == MAX_ATTEMPTS - 1:
                reply = yield from reply_to_too_broad(message)
                return {"intent": "sql_query", "reply": reply, "sql": None}
            feedback = (
                f"The previous query:\n{sql}\nwould return {count} rows, which is too many "
                f"(max {max_rows} for {'an aggregate' if max_rows == AGGREGATE_ROW_LIMIT else 'a raw reading'} "
                f"query). Rewrite it as a coarser aggregate (e.g. daily instead of hourly buckets) or narrow "
                "the time range."
            )
            continue

        result = db.execute(text(sql))
        rows = result.fetchall()
        columns = list(result.keys())
        if not rows:
            return {"intent": "sql_query", "reply": "I didn't find any data matching that question.", "sql": sql}
        yield {"type": "stage", "stage": "summarizing"}
        reply = yield from summarize_results(message, columns, rows)
        return {"intent": "sql_query", "reply": reply, "sql": sql}

    reply = yield from reply_to_too_broad(message)
    return {"intent": "sql_query", "reply": reply, "sql": None}


def generate_sql(message: str, history: list[tuple[str, str]] = [], feedback: str | None = None) -> str:
    now = datetime.now(timezone.utc).strftime("%A, %B %-d, %Y, %H:%M UTC")
    messages = [
        {"role": "system", "content": SQL_SYSTEM_PROMPT_TEMPLATE.format(now=now)},
        *history_to_messages(history),
        {"role": "user", "content": message},
    ]
    if feedback:
        messages.append({"role": "user", "content": feedback})

    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=1000,
        messages=messages,
    )
    sql = response.choices[0].message.content.strip()
    return sql.removeprefix("```sql").removesuffix("```").strip()


def validate_readonly(sql: str) -> None:
    if not sql.lstrip().upper().startswith("SELECT"):
        raise ValueError("Generated query is not a SELECT statement")
    if FORBIDDEN_SQL.search(sql):
        raise ValueError("Generated query contains a forbidden keyword")


def units_for_columns(columns: list[str]) -> dict[str, str]:
    """Map each result column to its real unit by matching it against
    COLUMN_UNITS's keys, since the SQL generator is instructed to keep the
    base column name inside its alias (e.g. avg_temperature_c) but may still
    vary case or add prefixes/suffixes around it."""
    units = {}
    for column in columns:
        for base_column, unit in COLUMN_UNITS.items():
            if base_column in column.lower():
                units[column] = unit
                break
    return units


def round_numeric(value):
    return round(value, 2) if isinstance(value, float) else value


def summarize_results(message: str, columns: list[str], rows: list):
    rows = [[round_numeric(v) for v in row] for row in rows]
    units = units_for_columns(columns)
    units_line = (
        "Units for these columns (state them exactly, never invent or guess a "
        f"different unit): {units}."
        if units
        else "None of these columns has a known physical unit; do not invent one."
    )

    if len(rows) == 1:
        style_instruction = (
            "Summarize the single result row in one short, friendly sentence for a "
            "non-technical user. Include the relevant numbers and units, using the "
            f"numbers exactly as given (already rounded). {units_line}"
        )
    else:
        style_instruction = (
            f"The query returned {len(rows)} rows. Present EVERY row, not just one, as a "
            "markdown table (GitHub-flavored markdown pipe table) with one column per "
            "field and one row per result row. Use short column headers with units in "
            f"parentheses taken from the mapping below, e.g. 'Temp (°C)'. {units_line} "
            "Use the numbers exactly as given (already rounded). Output ONLY the markdown "
            "table, no surrounding prose. Do not collapse multiple rows into a single "
            "summary sentence."
        )

    messages = [
        {
            "role": "system",
            "content": f"{style_instruction} {STYLE_RULE}",
        },
        {
            "role": "user",
            "content": f"Question: {message}\nColumns: {columns}\nRows: {rows[:20]}",
        },
    ]
    return (yield from stream_reply(messages, max_tokens=900))
