"""
Text-to-SQL chatbot for weather station queries.

Flow:
1. Classify the message as a greeting/small-talk, a station-info question,
   or a data question. Classification is done by the LLM; a regex-based
   keyword match is used only as a fallback if that call fails.
2. Greetings/station-info replies are generated by the LLM (grounded with
   static station facts as context, not returned verbatim).
3. Data questions are turned into a read-only SQL query by the LLM, given
   the DB schema, then executed and summarized back into natural language.

Uses Ollama Cloud (gpt-oss:20b-cloud) via its OpenAI-compatible API instead
of a paid LLM API — free tier, no AWS compute to host a model ourselves.
See https://ollama.com/pricing and https://docs.ollama.com/cloud.

Safety constraints on generated SQL:
- Only SELECT statements are allowed (checked before execution).
- Only whitelisted tables/columns are exposed in the prompt schema.
- Query runs against a DB role with SELECT-only privileges (see README).
- A LIMIT is enforced if the model omits one.
"""

import json
import re

from openai import OpenAI
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.config import settings

client = OpenAI(base_url="https://ollama.com/v1", api_key=settings.ollama_api_key)

MODEL = "gpt-oss:20b-cloud"

SCHEMA_DESCRIPTION = """
Table: readings (one row per station per second)
  - time            TIMESTAMPTZ  -- when the reading was taken
  - station_id       INTEGER      -- FK to stations.id
  - temperature_c    DOUBLE PRECISION
  - humidity_pct     DOUBLE PRECISION
  - pressure_hpa     DOUBLE PRECISION
  - wind_speed_ms    DOUBLE PRECISION
  - wind_dir_deg     DOUBLE PRECISION
  - noise_db         DOUBLE PRECISION
  - pm2_5_ugm3       DOUBLE PRECISION
  - pm10_ugm3        DOUBLE PRECISION

Table: stations
  - id          SERIAL PRIMARY KEY
  - name        TEXT
  - location    TEXT
  - latitude    DOUBLE PRECISION
  - longitude   DOUBLE PRECISION
  - created_at  TIMESTAMPTZ  -- when the station was registered
"""

STATION_FACTS = """
This weather station is a Raspberry Pi based setup that measures temperature,
humidity, atmospheric pressure, wind speed/direction, noise level, and
PM2.5/PM10 particulate matter concentration once per second, and streams the
readings to a cloud database in real time. Users can ask this chatbot
questions about the station's recorded data in natural language.
"""

GREETING_PATTERNS = re.compile(
    r"^\s*(hi|hello|hey|good (morning|afternoon|evening)|greetings)\b", re.IGNORECASE
)
STATION_INFO_PATTERNS = re.compile(
    r"\b(what (are|is) you|who are you|what do you do|tell me about (this|the) station|how does (this|the) station work|what.*(this )?(app|application) (do|for))\b",
    re.IGNORECASE,
)

INTENTS = ("greeting", "station_info", "data_question")

STYLE_RULE = "Do not use emojis. Do not use em dashes or double hyphens (--); use a comma or period instead."

CLASSIFY_SYSTEM_PROMPT = f"""Classify the user's message into exactly one intent:
- "greeting": small talk / hello.
- "station_info": a question about what this chatbot or weather station is/does/can do.
- "data_question": a question asking about actual sensor readings or historical data.

Respond with ONLY a JSON object: {{"intent": "<one of {list(INTENTS)}>"}}"""

SQL_SYSTEM_PROMPT = f"""You are a SQL generator for a PostgreSQL weather database.
Schema:
{SCHEMA_DESCRIPTION}

Rules:
- Output ONLY a single read-only SQL SELECT statement, nothing else — no
  explanation, no markdown fences, no commentary before or after.
- Never use INSERT, UPDATE, DELETE, DROP, ALTER, or any DDL/DML.
- Always include a LIMIT (max 1000) unless the query is an aggregate that
  returns one row.
- Use time-bucketing (date_trunc) for "per day/week" style questions.
- Default to the most recent station if none is named.
"""

FORBIDDEN_SQL = re.compile(
    r"\b(insert|update|delete|drop|alter|truncate|grant|revoke|create)\b", re.IGNORECASE
)


def history_to_messages(history: list[tuple[str, str]]) -> list[dict]:
    return [
        {"role": "assistant" if role == "assistant" else "user", "content": text}
        for role, text in history
    ]


def classify_intent(message: str, history: list[tuple[str, str]]) -> str:
    try:
        response = client.chat.completions.create(
            model=MODEL,
            max_tokens=200,
            extra_body={"reasoning_effort": "low"},
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": CLASSIFY_SYSTEM_PROMPT},
                *history_to_messages(history),
                {"role": "user", "content": message},
            ],
        )
        intent = json.loads(response.choices[0].message.content)["intent"]
        if intent in INTENTS:
            return intent
    except Exception:
        pass

    if GREETING_PATTERNS.search(message):
        return "greeting"
    if STATION_INFO_PATTERNS.search(message):
        return "station_info"
    return "data_question"


def reply_to_greeting(message: str) -> str:
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=300,
        extra_body={"reasoning_effort": "low"},
        messages=[
            {
                "role": "system",
                "content": f"You are a friendly assistant for a home weather station app. Reply in one short sentence to the user's greeting and invite them to ask about temperature, humidity, pressure, or other readings. {STYLE_RULE}",
            },
            {"role": "user", "content": message},
        ],
    )
    return response.choices[0].message.content.strip()


def reply_to_station_info(message: str) -> str:
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=600,
        extra_body={"reasoning_effort": "low"},
        messages=[
            {
                "role": "system",
                "content": f"You are the assistant for a home weather station app. Answer the user's question about the station/app in 3 sentences or fewer, using these facts:\n{STATION_FACTS}\n{STYLE_RULE}",
            },
            {"role": "user", "content": message},
        ],
    )
    return response.choices[0].message.content.strip()


def classify_and_reply(message: str, db: Session, history: list[tuple[str, str]] = []) -> dict:
    intent = classify_intent(message, history)

    if intent == "greeting":
        return {"intent": "greeting", "reply": reply_to_greeting(message), "sql": None}

    if intent == "station_info":
        return {"intent": "station_info", "reply": reply_to_station_info(message), "sql": None}

    return answer_data_question(message, db, history)


def answer_data_question(message: str, db: Session, history: list[tuple[str, str]] = []) -> dict:
    sql = generate_sql(message, history)
    try:
        validate_readonly(sql)
        result = db.execute(text(sql))
        rows = result.fetchall()
        columns = list(result.keys())
    except Exception:
        db.rollback()
        sql = generate_sql(message, history)
        validate_readonly(sql)
        result = db.execute(text(sql))
        rows = result.fetchall()
        columns = list(result.keys())

    reply = summarize_results(message, columns, rows)
    return {"intent": "sql_query", "reply": reply, "sql": sql}


def generate_sql(message: str, history: list[tuple[str, str]] = []) -> str:
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=1000,
        messages=[
            {"role": "system", "content": SQL_SYSTEM_PROMPT},
            *history_to_messages(history),
            {"role": "user", "content": message},
        ],
    )
    sql = response.choices[0].message.content.strip()
    return sql.removeprefix("```sql").removesuffix("```").strip()


def validate_readonly(sql: str) -> None:
    if not sql.lstrip().upper().startswith("SELECT"):
        raise ValueError("Generated query is not a SELECT statement")
    if FORBIDDEN_SQL.search(sql):
        raise ValueError("Generated query contains a forbidden keyword")


def summarize_results(message: str, columns: list[str], rows: list) -> str:
    if not rows:
        return "I didn't find any data matching that question."

    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=400,
        extra_body={"reasoning_effort": "low"},
        messages=[
            {
                "role": "system",
                "content": f"Summarize the SQL query result in one short, friendly sentence for a non-technical user. Include the relevant numbers and units. {STYLE_RULE}",
            },
            {
                "role": "user",
                "content": f"Question: {message}\nColumns: {columns}\nRows: {rows[:20]}",
            },
        ],
    )
    return response.choices[0].message.content.strip()
