"""
Text-to-SQL chatbot for weather station queries.

Flow:
1. Classify the message as small talk (greetings/thanks/acknowledgments), a
   station-info question, or a data question. Classification is done by the
   LLM; a regex-based keyword match is used only as a fallback if that call
   fails.
2. Small-talk/station-info replies are generated by the LLM (grounded with
   static station facts and, for small talk, the conversation history so it
   can tell an opener from a closing acknowledgment).
3. Data questions are turned into a read-only SQL query by the LLM, given
   the DB schema, then executed and summarized back into natural language.

Uses Ollama Cloud (gpt-oss:20b-cloud) via its OpenAI-compatible API instead
of a paid LLM API — free tier, no AWS compute to host a model ourselves.
See https://ollama.com/pricing and https://docs.ollama.com/cloud.

Safety constraints on generated SQL:
- Only SELECT statements are allowed (checked before execution).
- Only whitelisted tables/columns are exposed in the prompt schema.
- Query runs against a DB role with SELECT-only privileges (see README).
- A LIMIT is enforced if the model omits one.

Streaming:
- The pipeline is exposed as `classify_and_reply`, a generator that yields
  progress dicts as the request moves through the pipeline (stage changes,
  reply tokens) and returns the final result dict (intent/reply/sql) via
  StopIteration.value. Callers that just want the final result (e.g. the
  internal COUNT check in answer_data_question) can drain the generator
  with `run_to_completion`.
"""

import json
import logging
import re

from openai import OpenAI
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.config import settings

logger = logging.getLogger(__name__)

client = OpenAI(base_url="https://ollama.com/v1", api_key=settings.ollama_api_key)

MODEL = "gpt-oss:20b-cloud"

SCHEMA_DESCRIPTION = """
Table: readings (one row per station per second)
  - time            TIMESTAMPTZ  -- when the reading was taken
  - station_id       INTEGER      -- FK to stations.id
  - temperature_c    DOUBLE PRECISION
  - humidity_pct     DOUBLE PRECISION
  - pressure_hpa     DOUBLE PRECISION
  - wind_speed_ms    DOUBLE PRECISION
  - wind_dir_deg     DOUBLE PRECISION
  - noise_db         DOUBLE PRECISION
  - pm2_5_ugm3       DOUBLE PRECISION
  - pm10_ugm3        DOUBLE PRECISION

Table: stations
  - id          SERIAL PRIMARY KEY
  - name        TEXT
  - location    TEXT
  - latitude    DOUBLE PRECISION
  - longitude   DOUBLE PRECISION
  - created_at  TIMESTAMPTZ  -- when the station was registered
"""

STATION_FACTS = """
This weather station is a Raspberry Pi based setup that measures temperature,
humidity, atmospheric pressure, wind speed/direction, noise level, and
PM2.5/PM10 particulate matter concentration once per second, and streams the
readings to a cloud database in real time. Users can ask this chatbot
questions about the station's recorded data in natural language.
"""

SMALL_TALK_PATTERNS = re.compile(
    r"^\s*(hi|hello|hey|good (morning|afternoon|evening)|greetings"
    r"|thanks|thank you|thx|ok(ay)?|cool|great|perfect|nice|got it|sounds good|no problem|you'?re welcome|bye|goodbye)\b",
    re.IGNORECASE,
)
STATION_INFO_PATTERNS = re.compile(
    r"\b(what (are|is) you|who are you|what do you do|tell me about (this|the) station|how does (this|the) station work|what.*(this )?(app|application) (do|for))\b",
    re.IGNORECASE,
)

INTENTS = ("small_talk", "station_info", "data_question", "unclear")

STYLE_RULE = "Do not use emojis. Do not use em dashes or double hyphens (--); use a comma or period instead."

DASH_PATTERN = re.compile(r"\s*(--|[–—])\s*")
TABLE_ROW_PATTERN = re.compile(r"^\s*\|?[\s:|-]+\|?\s*$")


def enforce_style(text: str) -> str:
    lines = text.split("\n")
    fixed_lines = [
        line if TABLE_ROW_PATTERN.match(line) else DASH_PATTERN.sub(", ", line)
        for line in lines
    ]
    return "\n".join(fixed_lines).strip()

CLASSIFY_SYSTEM_PROMPT = f"""Classify the user's message into exactly one intent:
- "small_talk": greetings, acknowledgments, thanks, or other conversational chatter with no
  information request (e.g. "hello", "thanks", "okay perfect", "great, thank you").
- "station_info": a question about what this chatbot or weather station is/does/can do.
- "data_question": a question asking about actual sensor readings or historical data.
- "unclear": anything else that doesn't fit the categories above, or is too vague to act on.

The message may be a short follow-up that only makes sense in light of the
conversation so far (e.g. "lowest" after a question about highest humidity,
or "what about wind?" after a data question). Read the conversation history
first and interpret the latest message as a continuation of it before
classifying: if the history shows the conversation was about sensor data,
prefer "data_question" over "unclear" for a short follow-up. Only classify
as "unclear" if the message is still ambiguous after considering the history.

Respond with ONLY a JSON object: {{"intent": "<one of {list(INTENTS)}>"}}"""

TOO_BROAD_SENTINEL = "TOO_BROAD"

SQL_SYSTEM_PROMPT = f"""You are a SQL generator for a PostgreSQL weather database.
Schema:
{SCHEMA_DESCRIPTION}

Rules:
- Output ONLY a single read-only SQL SELECT statement, nothing else — no
  explanation, no markdown fences, no commentary before or after.
- Never use INSERT, UPDATE, DELETE, DROP, ALTER, or any DDL/DML.
- Always include a LIMIT (max 1000) unless the query is an aggregate that
  returns one row.
- Use time-bucketing (date_trunc) for "per day/week" style questions.
- Default to the most recent station if none is named.
- The latest message may be a short follow-up that only makes sense in light
  of the conversation history (e.g. "lowest" after a question about highest
  humidity means "lowest humidity"; "what about last month?" reuses the
  metric from the prior question with a new time range). Resolve the message
  against the conversation history before generating SQL.
- readings has one row per station per second, so it grows very large. If the
  user asks for all raw readings with no meaningful time bound or filter (e.g.
  "show me all the data", "every reading ever recorded", "dump the whole
  table"), do NOT generate a query. Instead output exactly: {TOO_BROAD_SENTINEL}
"""

FORBIDDEN_SQL = re.compile(
    r"\b(insert|update|delete|drop|alter|truncate|grant|revoke|create)\b", re.IGNORECASE
)


def history_to_messages(history: list[tuple[str, str]]) -> list[dict]:
    return [
        {"role": "assistant" if role == "assistant" else "user", "content": text}
        for role, text in history
    ]


def run_to_completion(generator):
    """Drain a pipeline generator, discarding progress events, and return its final result."""
    try:
        while True:
            next(generator)
    except StopIteration as stop:
        return stop.value


def classify_intent(message: str, history: list[tuple[str, str]]) -> str:
    try:
        response = client.chat.completions.create(
            model=MODEL,
            max_tokens=200,
            extra_body={"reasoning_effort": "high"},
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": CLASSIFY_SYSTEM_PROMPT},
                *history_to_messages(history),
                {"role": "user", "content": message},
            ],
        )
        raw_content = response.choices[0].message.content
        intent = json.loads(raw_content)["intent"]
        if intent in INTENTS:
            return intent
        logger.warning(
            "classify_intent: LLM returned unrecognized intent %r for message %r (raw: %r)",
            intent, message, raw_content,
        )
    except Exception:
        logger.exception("classify_intent: LLM classification call failed for message %r", message)

    if SMALL_TALK_PATTERNS.search(message):
        return "small_talk"
    if STATION_INFO_PATTERNS.search(message):
        return "station_info"
    return "unclear"


def stream_reply(messages: list[dict], max_tokens: int, reasoning_effort: str = "low"):
    """Stream a chat completion, yielding {"type": "token", "text": ...} per chunk.

    Returns (via StopIteration.value) the full, style-enforced reply text.
    """
    stream = client.chat.completions.create(
        model=MODEL,
        max_tokens=max_tokens,
        extra_body={"reasoning_effort": reasoning_effort},
        messages=messages,
        stream=True,
    )
    chunks = []
    for chunk in stream:
        delta = chunk.choices[0].delta.content
        if delta:
            chunks.append(delta)
            yield {"type": "token", "text": delta}
    return enforce_style("".join(chunks))


def reply_to_small_talk(message: str, history: list[tuple[str, str]]):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a friendly assistant for a weather station app. The user's latest "
                "message is small talk (a greeting, thanks, or a short acknowledgment), not a "
                "data question. Look at the conversation history to tell whether this opens the "
                "conversation or just closes out a prior answer. If it opens the conversation, "
                "reply in one short sentence and invite them to ask about temperature, humidity, "
                "pressure, or other readings. If it just acknowledges/thanks you for a prior "
                f"answer, reply with a brief one-sentence acknowledgment and nothing more, do "
                f"not restate or re-summarize the previous answer. {STYLE_RULE}"
            ),
        },
        *history_to_messages(history),
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=300))


def reply_to_unclear(message: str):
    messages = [
        {
            "role": "system",
            "content": f"You are the assistant for a weather station app. The user's message doesn't clearly ask about the station's data or about the app itself. In one short sentence, say you didn't understand and invite them to ask about the station. {STYLE_RULE}",
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=300))


def reply_to_station_info(message: str):
    messages = [
        {
            "role": "system",
            "content": f"You are the assistant for a weather station app. Answer the user's question about the station/app in 3 sentences or fewer, using these facts:\n{STATION_FACTS}\n{STYLE_RULE}",
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=600))


def classify_and_reply(message: str, db: Session, history: list[tuple[str, str]] = []):
    yield {"type": "stage", "stage": "classifying"}
    intent = classify_intent(message, history)

    if intent == "small_talk":
        reply = yield from reply_to_small_talk(message, history)
        return {"intent": "small_talk", "reply": reply, "sql": None}

    if intent == "station_info":
        reply = yield from reply_to_station_info(message)
        return {"intent": "station_info", "reply": reply, "sql": None}

    if intent == "unclear":
        reply = yield from reply_to_unclear(message)
        return {"intent": "unclear", "reply": reply, "sql": None}

    result = yield from answer_data_question(message, db, history)
    return result


MAX_ROWS = 1000


def reply_to_too_broad(message: str):
    messages = [
        {
            "role": "system",
            "content": (
                "You are the assistant for a weather station app. Readings are recorded "
                "once per second per station, so the user's request below would require "
                "returning an unbounded/huge amount of raw data. Explain that to the user "
                "referencing what they specifically asked for, then propose 2-3 concrete "
                "narrower alternatives based on their exact wording (e.g. a specific time "
                f"range, a specific station, or an aggregate like an average/max/min instead "
                f"of raw rows). {STYLE_RULE}"
            ),
        },
        {"role": "user", "content": message},
    ]
    return (yield from stream_reply(messages, max_tokens=600, reasoning_effort="medium"))


MAX_ATTEMPTS = 3


def answer_data_question(message: str, db: Session, history: list[tuple[str, str]] = []):
    feedback = None

    for attempt in range(MAX_ATTEMPTS):
        yield {"type": "stage", "stage": "generating_sql" if attempt == 0 else "retrying_query"}
        sql = generate_sql(message, history, feedback)

        if sql.strip().upper() == TOO_BROAD_SENTINEL:
            reply = yield from reply_to_too_broad(message)
            return {"intent": "sql_query", "reply": reply, "sql": None}

        yield {"type": "stage", "stage": "running_query"}
        try:
            validate_readonly(sql)
            count = db.scalar(text(f"SELECT COUNT(*) FROM ({sql.rstrip(';')}) AS sub"))
        except Exception as e:
            db.rollback()
            feedback = f"The previous query:\n{sql}\nfailed with error: {e}. Fix it."
            continue

        if count > MAX_ROWS:
            if attempt == MAX_ATTEMPTS - 1:
                reply = yield from reply_to_too_broad(message)
                return {"intent": "sql_query", "reply": reply, "sql": None}
            feedback = (
                f"The previous query:\n{sql}\nwould return {count} rows, which is too many "
                f"(max {MAX_ROWS}). Rewrite it as an aggregate (e.g. an average/min/max per "
                "hour/day/week) or narrow the time range instead of returning raw rows."
            )
            continue

        result = db.execute(text(sql))
        rows = result.fetchall()
        columns = list(result.keys())
        if not rows:
            return {"intent": "sql_query", "reply": "I didn't find any data matching that question.", "sql": sql}
        yield {"type": "stage", "stage": "summarizing"}
        reply = yield from summarize_results(message, columns, rows)
        return {"intent": "sql_query", "reply": reply, "sql": sql}

    reply = yield from reply_to_too_broad(message)
    return {"intent": "sql_query", "reply": reply, "sql": None}


def generate_sql(message: str, history: list[tuple[str, str]] = [], feedback: str | None = None) -> str:
    messages = [
        {"role": "system", "content": SQL_SYSTEM_PROMPT},
        *history_to_messages(history),
        {"role": "user", "content": message},
    ]
    if feedback:
        messages.append({"role": "user", "content": feedback})

    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=1000,
        messages=messages,
    )
    sql = response.choices[0].message.content.strip()
    return sql.removeprefix("```sql").removesuffix("```").strip()


def validate_readonly(sql: str) -> None:
    if not sql.lstrip().upper().startswith("SELECT"):
        raise ValueError("Generated query is not a SELECT statement")
    if FORBIDDEN_SQL.search(sql):
        raise ValueError("Generated query contains a forbidden keyword")


def summarize_results(message: str, columns: list[str], rows: list):
    if len(rows) == 1:
        style_instruction = "Summarize the single result row in one short, friendly sentence for a non-technical user. Include the relevant numbers and units."
    else:
        style_instruction = (
            f"The query returned {len(rows)} rows. Present EVERY row, not just one, as a "
            "markdown table (GitHub-flavored markdown pipe table) with one column per "
            "field and one row per result row. Use short column headers with units in "
            "parentheses (e.g. 'Temp (C)'). Round numbers to 1-2 decimal places. Output "
            "ONLY the markdown table, no surrounding prose. Do not collapse multiple rows "
            "into a single summary sentence."
        )

    messages = [
        {
            "role": "system",
            "content": f"{style_instruction} {STYLE_RULE}",
        },
        {
            "role": "user",
            "content": f"Question: {message}\nColumns: {columns}\nRows: {rows[:20]}",
        },
    ]
    return (yield from stream_reply(messages, max_tokens=900))
